### ISSUE TITLE
Heads up, mp4 is corrupt 

### ISSUE THREAD

**Issue by Thomashighbaugh** [danielnehrig/nvim#6]
![20211007_030055](https://user-images.githubusercontent.com/32242061/136363394-aade95ba-8bc0-4d49-b0a4-da378e554de7.png)

**Comment by danielnehrig** [comment]
thanks for the info
my guess is you lack the needed containers to encode the format
since it works for me i'll change to a different container thanks for letting me know
https://i.imgur.com/Nvqfryr.png

**Comment by danielnehrig** [comment]
can you check if it works for you now ?
